modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "rubychatcalculator"
version = "${version}"
displayName = "Ruby Chat Calculator"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.rubychatcalculator]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rubychatcalculator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
